version: '3.8'

services:
  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=yourpassword
    command: redis-server --requirepass Dilip$202
  # redis:
  #   image: 'redis:alpine'
  #   container_name: redis
  #   ports:
  #     - '6379:6379'

  mongo:
    image: 'mongo'
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    container_name: backend
    ports:
      - '3001:3001'
    depends_on:
      - redis
      - mongo
    environment:
      - REDIS_HOST=redis
      - MONGO_URL=mongodb://mongo:27017/collaborativeDocs

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  mongo-data:

